<a href="https://colab.research.google.com/github/Chithra05/Libraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3],dtype=float)
print(arr)

[1. 2. 3.]


In [ ]:
fruit_cost=[20,30,50,80]
vegetable_cost=[10,50,90,40]
fruit_np=np.array(fruit_cost)
vegetable_np=np.array(vegetable_cost)
print(fruit_np)

[20 30 50 80]


In [ ]:
print(vegetable_cost)

[10, 50, 90, 40]


In [ ]:
print(type(fruit_np))

<class 'numpy.ndarray'>


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr>5])

[6 7 8 9]


In [ ]:
a=np.array([[1,2,3,4],[5,4,6,7],[8,6,5,4]])
print(a)

[[1 2 3 4]
 [5 4 6 7]
 [8 6 5 4]]


In [ ]:
x=np.array([1,2])
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
x1=np.array([1,2])
print(x1.dtype)

int64


In [ ]:
x2=np.array([1.0,2.0])
print(x2.dtype)

float64


In [ ]:
x3=np.array([[1,5],[5,4]])
x4=np.array([[5,6],[8,4]])
print(x3+x4)

[[ 6 11]
 [13  8]]


In [ ]:
print(np.add(x3,x4))

[[ 6 11]
 [13  8]]


In [ ]:
print(x3*x4)

[[ 5 30]
 [40 16]]


In [ ]:
print(x3/x4)

[[0.2        0.83333333]
 [0.625      1.        ]]


In [ ]:
#Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

219
219
